title: Trial Bundle
filename: Trial_Bundle.pdf
filenameIdentifier: /case_details/filename_identifier
hasTableOfContents: true
hasCoversheets: false
hasFolderCoversheets: true
paginationStyle: bottomRight
pageNumberFormat: pageRange
documentNameValue: /documentFileName
folders:
  - name: Trial Documents
    documents:
      - type: documentSet
        property: /claimant1TrialDocuments
        filters:
          - property: /documentType
            value: WITNESS_SUMMARY
          - property: /documentType
            value: CHRONOLOGY
          - property: /documentType
            value: TIMETABLE
  - name: Statements of Case
    documents:
      - type: documentSet
        property: /statementsOfCaseDocuments
  - name: Orders
    documents:
      - type: documentSet
        property: /ordersDocuments
  - name: Witness Statements
    folders:
      - name: CL 1 Witness Statements
        documents:
          - type: documentSet
            property: /claimant1WitnessStatements
      - name: CL 2 Witness Statements
        documents:
          - type: documentSet
            property: /claimant2WitnessStatements
      - name: DF 1 Witness Statements
        documents:
          - type: documentSet
            property: /defendant1WitnessStatements
      - name: DF 2 Witness Statements
        documents:
          - type: documentSet
            property: /defendant2WitnessStatements
  - name: Expert Evidence
    folders:
      - name: CL 1 Experts
        documents:
          - type: documentSet
            property: /claimant1ExpertEvidence
      - name: CL 2 Experts
        documents:
          - type: documentSet
            property: /claimant2ExpertEvidence
      - name: DF 1 Experts
        documents:
          - type: documentSet
            property: /defendant1ExpertEvidence
      - name: DF 2 Experts
        documents:
          - type: documentSet
            property: /defendant2ExpertEvidence
  - name: Joint statements of experts/single joint expert report
    documents:
      - type: documentSet
        property: /jointStatementOfExperts
  - name: Disclosed Documents
    folders:
      - name: CL 1 Documents they intend to rely on
        documents:
          - type: documentSet
            property: /claimant1DisclosedDocuments
      - name: CL 2 Documents they intend to rely on
        documents:
          - type: documentSet
            property: /claimant1DisclosedDocuments
      - name: DF 1 Documents they intend to rely on
        documents:
          - type: documentSet
            property: /defendant1DisclosedDocuments
      - name: DF 2 Documents they intend to rely on
        documents:
          - type: documentSet
            property: /defendant2DisclosedDocuments
  - name: Costs Budgets
    folders:
      - name: CL 1 Costs Budget
        documents:
          - type: documentSet
            property: /claimant1CostsBudgets
      - name: CL 2 Costs Budget
        documents:
          - type: documentSet
            property: /claimant2CostsBudgets
      - name: DF 1 Costs Budget
        documents:
          - type: documentSet
            property: /defendant1CostsBudgets
      - name: DF 2 Costs Budget
        documents:
          - type: documentSet
            property: /defendant2CostsBudgets