title: IAC Remitted Hearing Bundle
filename: remitted-hearing-bundle.pdf
filenameIdentifier: /case_details/case_data/bundleFileNamePrefix
coverpageTemplate: TB-IAC-HRN-ENG-00514.docx
hasTableOfContents: true
hasCoversheets: true
documentNameValue: /document/document_filename
documentLinkValue: /document
sort:
  field: /dateUploaded
  order: ascending
hasFolderCoversheets: true
pageNumberFormat: numberOfPages
folders:
  - name: Appellant additional evidence following FTPA
    documents:
      - type: documentSet
        property: /appAdditionalEvidenceDocs
  - name: Respondent additional evidence following FTPA
    documents:
      - type: documentSet
        property: /respAdditionalEvidenceDocs
  - name: Appellant FTPA documents
    documents:
      - type: documentSet
        property: /ftpaAppellantDocuments
  - name: Respondent FTPA documents
    documents:
      - type: documentSet
        property: /ftpaRespondentDocuments
  - name: Appellant evidence after the hearing bundle
    documents:
      - type: documentSet
        property: /appellantAddendumEvidenceDocs
  - name: Respondent evidence after the hearing bundle
    documents:
      - type: documentSet
        property: /respondentAddendumEvidenceDocs
  - name: Previous bundle
    documents:
      - type: documentSet
        property: /hearingDocuments
        filters:
          - property: /tag
            value: hearingBundle
  - name: Decisions and reasons documents
    documents:
      - type: documentSet
        property: /latestDecisionAndReasonsDocuments
  - name: Remittal documents
    documents:
      - type: documentSet
        property: /latestRemittalDocuments
  - name: Reheard hearing documents
    documents:
      - type: documentSet
        property: /latestReheardHearingDocuments
