title: /case_details/id
filename: PRLBundle
filenameIdentifier: /case_details/id
coverpageTemplate: FL-PRL-LET-ENG-CoverPage.docx
hasTableOfContents: true
hasCoversheets: true
hasFolderCoversheets: true
paginationStyle: bottomRight
pageNumberFormat: pageRange
documentNameValue: /documentFileName
folders:
  - name: Orders
    folders:
      - name: Orders Submitted with Application
        documents:
          - type: documentSet
            property: /data/orders
  - name: Preliminary Documents
    folders:
      - name: Position statements
        folders:
          - name: Applicant Position Statement
            documents:
              - type: documentSet
                property: /data/citizenUploadedDocuments
                filters:
                  - property: /documentGroup
                    value: applicantPositionStatements
          - name: Respondent Position Statement
            documents:
              - type: documentSet
                property: /data/citizenUploadedDocuments
                filters:
                  - property: /documentGroup
                    value: respondentPositionStatements
  - name: Applications
    folders:
      - name: Applicant Documents
        folders:
          - name: Applicant Application
            documents:
              - type: documentSet
                property: /data/applications
          - name: Applicant C1A Application
            documents:
              - type: documentSet
                property: /data/applications
                filters:
                  - property: /documentGroup
                    value: applicantC1AApplication
          - name: Miam Certificate
            documents:
              - type: documentSet
                property: /data/applications
                filters:
                  - property: /documentGroup
                    value: applicantMiamCertificate
          - name: Previous Orders Submitted With Application
            documents:
              - type: documentSet
                property: /data/applications
                filters:
                  - property: /documentGroup
                    value: applicantPreviousOrdersSubmittedWithApplication
      - name: Respondent Documents
        folders:
          - name: Respondent Application
            documents:
              - type: documentSet
                property: /data/applications
                filters:
                  - property: /documentGroup
                    value: c7Documents
  - name: Witness Statement And Evidence
    folders:
      - name: Applicant's Statements
        folders:
          - name: Witness Statements
            documents:
              - type: documentSet
                property: /data/citizenUploadedDocuments
                filters:
                  - property: /documentGroup
                    value: applicantWitnessStatements
              - type: documentSet
                property: /data/otherDocumentsUploadedByCourtAdmin
                filters:
                  - property: /documentGroup
                    value: applicantStatementDocsUploadedByCourtAdmin
          - name: Letters from School
            documents:
              - type: documentSet
                property: /data/citizenUploadedDocuments
                filters:
                  - property: /documentGroup
                    value: applicantLettersFromSchool
          - name: Other Evidences
            documents:
              - type: documentSet
                property: /data/citizenUploadedDocuments
                filters:
                  - property: /documentGroup
                    value: applicantEmailsOrScreenshotsOrImagesOrOtherMediaFiles
      - name: Respondent's Statements
        folders:
          - name: Witness Statements
            documents:
              - type: documentSet
                property: /data/citizenUploadedDocuments
                filters:
                  - property: /documentGroup
                    value: respondentWitnessStatements
          - name: Letters from School
            documents:
              - type: documentSet
                property: /data/citizenUploadedDocuments
                filters:
                  - property: /documentGroup
                    value: respondentLettersFromSchool
          - name: Other Evidences
            documents:
              - type: documentSet
                property: /data/citizenUploadedDocuments
                filters:
                  - property: /documentGroup
                    value: respondentEmailsOrScreenshotsOrImagesOrOtherMediaFiles
      - name: Other Witness Statements
        documents:
          - type: documentSet
            property: /data/citizenUploadedDocuments
            filters:
              - property: /documentGroup
                value: otherWitnessStatements
  - name: CAFCASS Report and Guardian
    folders:
      - name: Other Documents
        documents:
          - type: documentSet
            property: /data/otherDocumentsUploadedByCourtAdmin
            filters:
              - property: /documentGroup
                value: cafcassReportsUploadedByCourtAdmin
  - name: Expert Reports
    folders:
      - name: Medical Reports
        documents:
          - type: documentSet
            property: /data/citizenUploadedDocuments
            filters:
              - property: /documentGroup
                value: expertMedicalReports
          - type: documentSet
            property: /data/otherDocumentsUploadedByCourtAdmin
            filters:
              - property: /documentGroup
                value: expertReportsUploadedByCourtAdmin
      - name: DNA Reports
        documents:
          - type: documentSet
            property: /data/citizenUploadedDocuments
            filters:
              - property: /documentGroup
                value: expertDNAReports
      - name: Medical Records
        documents:
          - type: documentSet
            property: /data/citizenUploadedDocuments
            filters:
              - property: /documentGroup
                value: expertMedicalRecords
      - name: Drug And Alcohol Tests(Toxicology)
        documents:
          - type: documentSet
            property: /data/citizenUploadedDocuments
            filters:
              - property: /documentGroup
                value: expertReportsForDrugAndAlcholTest
      - name: Police Reports
        documents:
          - type: documentSet
            property: /data/citizenUploadedDocuments
            filters:
              - property: /documentGroup
                value: policeReports
