title: PRL Bundle
filename: Bundle
filenameIdentifier: /case_details/bundle_name
coverpageTemplate: FL-PRL-LET-ENG-CoverPage.docx
hasTableOfContents: true
hasCoversheets: false
hasFolderCoversheets: true
paginationStyle: bottomRight
pageNumberFormat: pageRange
documentNameValue: /documentFileName
folders:
  - name: Preliminary Documents
    documents:
      - type: documentSet
        property: /data/allOtherDocuments
        filters:
          - property: /documentGroup
            value: caseSummary
      - type: documentSet
        property: /data/allOtherDocuments
        filters:
          - property: /documentGroup
            value: positionStatements
      - type: documentSet
        property: /data/allOtherDocuments
        filters:
          - property: /documentGroup
            value: fm5Statements
  - name: Applications and Orders
    documents:
      - type: documentSet
        property: /data/applications
        filters:
          - property: /documentGroup
            value: applicantApplication
      - type: documentSet
        property: /data/applications
        filters:
          - property: /documentGroup
            value: applicantC1AApplication
      - type: documentSet
        property: /data/allOtherDocuments
        filters:
          - property: /documentGroup
            value: applicantC1AResponse
      - type: documentSet
        property: /data/allOtherDocuments
        filters:
          - property: /documentGroup
            value: applicantAWPDocuments
      - type: documentSet
        property: /data/allOtherDocuments
        filters:
          - property: /documentGroup
            value: applicantMiamCertificate
      - type: documentSet
        property: /data/allOtherDocuments
        filters:
          - property: /documentGroup
            value: applicantPreviousOrdersSubmittedWithApplication
      - type: documentSet
        property: /data/allOtherDocuments
        filters:
          - property: /documentGroup
            value: respondentApplication
      - type: documentSet
        property: /data/allOtherDocuments
        filters:
          - property: /documentGroup
            value: respondentC1AApplication
      - type: documentSet
        property: /data/allOtherDocuments
        filters:
          - property: /documentGroup
            value: respondentC1AResponse
      - type: documentSet
        property: /data/allOtherDocuments
        filters:
          - property: /documentGroup
            value: respondentAWPDocuments
      - type: documentSet
        property: /data/allOtherDocuments
        filters:
          - property: /documentGroup
            value: respondentPreviousOrdersSubmittedWithApplication
      - type: documentSet
        property: /data/orders
        filters:
          - property: /documentGroup
            value: ordersSubmittedWithApplication
      - type: documentSet
        property: /data/allOtherDocuments
        filters:
          - property: /documentGroup
            value: transcriptsOfJudgements
      - type: documentSet
        property: /data/allOtherDocuments
        filters:
          - property: /documentGroup
            value: magistrateFactAndReasons
  - name: Witness statement and evidence
    documents:
      - type: documentSet
        property: /data/allOtherDocuments
        filters:
          - property: /documentGroup
            value: applicantWitnessStatements
      - type: documentSet
        property: /data/allOtherDocuments
        filters:
          - property: /documentGroup
            value: respondentWitnessStatements
      - type: documentSet
        property: /data/allOtherDocuments
        filters:
          - property: /documentGroup
            value: otherWitnessStatements
  - name: Expert Reports including Guardian (CAFCASS)
    documents:
      - type: documentSet
        property: /data/allOtherDocuments
        filters:
          - property: /documentGroup
            value: safeguardingLetter
      - type: documentSet
        property: /data/allOtherDocuments
        filters:
          - property: /documentGroup
            value: section7Report
      - type: documentSet
        property: /data/allOtherDocuments
        filters:
          - property: /documentGroup
            value: childImpactReport1
      - type: documentSet
        property: /data/allOtherDocuments
        filters:
          - property: /documentGroup
            value: childImpactReport2
      - type: documentSet
        property: /data/allOtherDocuments
        filters:
          - property: /documentGroup
            value: cafcassSection37Report
      - type: documentSet
        property: /data/allOtherDocuments
        filters:
          - property: /documentGroup
            value: sixteenARiskAssessment
      - type: documentSet
        property: /data/allOtherDocuments
        filters:
          - property: /documentGroup
            value: guardianReport
      - type: documentSet
        property: /data/allOtherDocuments
        filters:
          - property: /documentGroup
            value: specialGuardianshipReport
      - type: documentSet
        property: /data/allOtherDocuments
        filters:
          - property: /documentGroup
            value: cafcassOtherDocuments
      - type: documentSet
        property: /data/allOtherDocuments
        filters:
          - property: /documentGroup
            value: laSection37Report
      - type: documentSet
        property: /data/allOtherDocuments
        filters:
          - property: /documentGroup
            value: laOtherDocuments
  - name: Other Documents
    documents:
      - type: documentSet
        property: /data/allOtherDocuments
        filters:
          - property: /documentGroup
            value: medicalReports
      - type: documentSet
        property: /data/allOtherDocuments
        filters:
          - property: /documentGroup
            value: dnaReports
      - type: documentSet
        property: /data/allOtherDocuments
        filters:
          - property: /documentGroup
            value: resultsOfHairStrandBloodTests
      - type: documentSet
        property: /data/allOtherDocuments
        filters:
          - property: /documentGroup
            value: policeDisclosures
      - type: documentSet
        property: /data/allOtherDocuments
        filters:
          - property: /documentGroup
            value: medicalRecords
      - type: documentSet
        property: /data/allOtherDocuments
        filters:
          - property: /documentGroup
            value: reportsForDrugAndAlcoholTest
      - type: documentSet
        property: /data/allOtherDocuments
        filters:
          - property: /documentGroup
            value: policeReport
      - type: documentSet
        property: /data/allOtherDocuments
        filters:
          - property: /documentGroup
            value: anyOtherDocuments
