title: PRL Bundle
filename: Bundle
filenameIdentifier: /case_details/bundle_name
coverpageTemplate: FL-PRL-LET-ENG-CoverPage.docx
hasTableOfContents: true
hasCoversheets: false
hasFolderCoversheets: true
paginationStyle: bottomRight
pageNumberFormat: pageRange
documentNameValue: /documentFileName
folders:
  - name: Applications and Orders
    documents:
      - type: documentSet
        property: /data/applications
        filters:
          - property: /documentGroup
            value: applicantApplication
      - type: documentSet
        property: /data/applications
        filters:
          - property: /documentGroup
            value: applicantC1AApplication