external_hostname = "jcm.ithc.platform.hmcts.net"
external_hostname_www = "www.jcm.ithc.platform.hmcts.net"
external_cert_name = "wildcard-ithc-platform-hmcts-net"
external_cert_vault_uri = "https://infra-vault-qa.vault.azure.net/"
managed_identity_object_id="0a73c7f0-a6e5-41a9-95d1-2b793ff0f8db"