idam_api_base_uri = "https://idam-api.platform.hmcts.net"
open_id_api_base_uri = "https://idam-api.platform.hmcts.net/o"
oidc_issuer_base_uri = "https://forgerock-am.service.core-compute-idam.internal:8443/openam/oauth2/hmcts"
enable_stitching_complete_callback="false"
managed_identity_object_id="82b164c9-e611-498d-8bd0-d3c01e8df3c8"
