idam_api_base_uri = "http://idam-api-idam-sprod.service.core-compute-idam-sprod.internal"
open_id_api_base_uri = "http://idam-api-idam-sprod.service.core-compute-idam-sprod.internal/o"
oidc_issuer_base_uri = "https://forgerock-am.service.core-compute-idam-sprod.internal:8443/openam/oauth2/hmcts"
capacity = "2"
enable_stitching_complete_callback="false"
